<?php

namespace Amz\VendorDirectFulfillmentShipping\Model;

use OpenAPI\Runtime\AbstractModel as AbstractModel;

/**
 * Details about a shipment.
 */
class ShipmentDetails extends AbstractModel
{
    /**
     * This field indicates the date of the departure of the shipment from vendor's
     * location. Vendors are requested to send ASNs within 30 minutes of departure from
     * their warehouse/distribution center or at least 6 hours prior to the appointment
     * time at the Amazon destination warehouse, whichever is sooner. Shipped date
     * mentioned in the Shipment Confirmation should not be in the future.
     *
     * @var string
     */
    public $shippedDate = null;

    /**
     * Indicate the shipment status.
     *
     * @var string
     */
    public $shipmentStatus = null;

    /**
     * Provide the priority of the shipment.
     *
     * @var bool
     */
    public $isPriorityShipment = null;

    /**
     * The vendor order number is a unique identifier generated by a vendor for their
     * reference.
     *
     * @var string
     */
    public $vendorOrderNumber = null;

    /**
     * Date on which the shipment is expected to reach the buyer's warehouse. It needs
     * to be an estimate based on the average transit time between the ship-from
     * location and the destination. The exact appointment time will be provided by
     * buyer and is potentially not known when creating the shipment confirmation.
     *
     * @var string
     */
    public $estimatedDeliveryDate = null;
}
